### ISSUE TITLE
Basic Example Fails to Log to StdErr

### ISSUE THREAD

**Issue by nt3rp** [FogCreek/logging#2]
This is probably an example of PEBKAC, but I'm trying to use this library using an extremely basic example, and it doesn't appear to be working. If I run the below, I don't see any output.

```
package main

import (
    "github.com/FogCreek/logging"
)

func main() {
    logging.Info("one")
    logging.Debug("two")
}
```

Even if I create a `StdErrAppender` explicitly, I get the same result:

```
func main() {
    logging.AddAppender(logging.NewStdOutAppender())
    logging.Info("one")
    logging.Debug("two")
}
```

Perhaps this is merely some missing documentation?

**Comment by sasbury** [comment]
Because we use a channel to pull logging out of the go routine you call the methods from, there can be a small delay between the logging call and the log printing. You can force the logging go routine to process everything by using logging.WaitForIncoming()

Hopefully that helps.

**Comment by nt3rp** [comment]
Ah, I see. That seems to work; thanks for the assistance. :smile:
